FROM php:8.2-fpm-alpine
WORKDIR /var/www/html

RUN apk add --no-cache icu-dev icu-data-full oniguruma-dev bash curl && docker-php-ext-install intl && docker-php-ext-install mbstring && docker-php-ext-install mysqli

RUN curl -s https://getcomposer.org/installer | php

COPY builds composer.json composer.lock phpunit.xml.dist preload.php spark ./
COPY app app/
COPY public public/
COPY tests tests/
COPY writable writable/

RUN chown -R www-data:www-data /var/www/html
RUN php composer.phar install